### ISSUE TITLE
Create a homepage for the stomach in the ICES sharepoint

### ISSUE THREAD

**Issue by cmspinto** [ices-tools-dev/STOM#12]

**Comment by neil-ices-dk** [comment]
can do that, just paste here all the info:

current stomach page for reference https://www.ices.dk/data/data-portals/Pages/Fish-stomach.aspx

- right hand links (call to actions)
- right hand links (others i.e. data license etc)
- image (if you have one) @370 pixels wide
- Tagline
- Body text

**Comment by cekv** [comment]
done
