### ISSUE TITLE
Change sentence structure on the manage page

### ISSUE THREAD

**Issue by cekv** [ices-tools-dev/STOM#16]
![Image](https://github.com/ices-tools-dev/STOM/assets/75067038/ba21ed27-2fcd-4b16-ae0f-370da666c824)

**Comment by cekv** [comment]
a)	Screen a stomach content data file for submission.
b)	View a list of your screenings.
c)	View a list of your submissions.
d)	View a list of all submissions from your organization.
e)	Are you managing any institution? (Needs improvement/ removal)
f)	Logout

**Comment by cmspinto** [comment]
Let's discuss this one in the next sprint

**Comment by cmspinto** [comment]
Done :)
