### ISSUE TITLE
Create key from CruisID in FI

### ISSUE THREAD

**Issue by cekv** [ices-tools-dev/STOM#4]
Create Key and also add a warning (SQL) to check previous submissions and warning if such is present

**Comment by cekv** [comment]
Key: CountryEDMOShipYearMonth

**Comment by evabrna** [comment]
@cmspinto I have made a check like that FROM (select  MIN(LineNumber)
AS LineNumber 
FROM RFI 
GROUP BY CruiseID  HAVING (COUNT(*) > 1)) as RFI

The CruiseID is not unique for the File
can you confirm if it is the correct way to do it?

**Comment by evabrna** [comment]
done
